CLASS zcl_33_record_logali_cm DEFINITION INHERITING FROM zcl_32_constr_cntr_logali_cm
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_33_record_logali_cm IMPLEMENTATION.

ENDCLASS.
