CLASS zcl_21_airplane_logali_cm DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS airplane_type ABSTRACT RETURNING VALUE(rv_airplane_type) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_21_airplane_logali_cm IMPLEMENTATION.
ENDCLASS.
